package grocito.wingstud.groctiodriver.response

data class PaidpaymentDetailsResponse(
        val base_income: Double,
        val bonus_amount: Double,
        val `data`: List<Data>,
        val hudibaba_fee: Double,
        val img_path: String,
        val message: String,
        val order_amount: Double,
        val slip: String,
        val status: Int,
        val transaction_id: String
) {
    data class Data(

            val job_id: String,
            val my_payment: String,
            val order_amount: String,

            val address_id: Int,
            val admin_commission: Double,
            val amount_per_km: Int,
            val bonus: Int,
            val cashback_amount: Int,
            val created_at: String,
            val d_p_d_amount: Int,
            val date: String,
            val delivery_boy_id: Int,
            val delivery_date: String,
            val delivery_time: String,
            val delivery_type: String,
            val distance: Int,
            val dock_no: String,
            val express_time: String,
            val extra_amount: Int,
            val gst_amount: Int,
            val id: String,
            val is_cod_submitted: Int,
            val net_amount: Double,
            val ord_payment_id: String,
            val order_id: String,
            val payment_amount: Int,
            val payment_mode: String,
            val payment_status: String,
            val reason: String,
            val seller_id: String,
            val sgst_amount: Double,
            val shipped_by: String,
            val shipped_date: String,
            val shipping_charge: Int,
            val status: String,
            val status_message: String,
            val sub_order_id: Any,
            val total_amount: Double,
            val transaction_id: String,
            val type: String,
            val updated_at: String,
            val user_id: Int,
            val wallet_amount: Int,
            val wallet_pay: Int,
            val wallet_use: Int,
            val warehouse_id: Int
    )
}